In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import isoweek

data_url = "https://www.sentiweb.fr/datasets/all/inc-7-PAY.csv"
raw_data = pd.read_csv(data_url, skiprows=1)
raw_data

,week,indicator,inc,inc_low,inc_up,inc100,inc100_low,inc100_up,geo_insee,geo_name
0,202425,7,12129,8130,16128,18,12,24,FR,France
1,202424,7,12731,9438,16024,19,14,24,FR,France
2,202423,7,14657,11339,17975,22,17,27,FR,France
3,202422,7,11628,8361,14895,17,12,22,FR,France
4,202421,7,9701,6851,12551,15,11,19,FR,France
5,202420,7,13661,10209,17113,20,15,25,FR,France
6,202419,7,10083,6413,13753,15,9,21,FR,France
7,202418,7,13438,9514,17362,20,14,26,FR,France
8,202417,7,15303,11219,19387,23,17,29,FR,France
9,202416,7,18138,13540,22736,27,20,34,FR,France
10,202415,7,24929,17315,32543,37,26,48,FR,France
11,202414,7,16181,12544,19818,24,19,29,FR,France
12,202413,7,18322,14206,22438,27,21,33,FR,France
13,202412,7,12818,9128,16508,19,13,25,FR,France
14,202411,7,15973,12400,19546,24,19,29,FR,France
15,202410,7,14301,10761,17841,21,16,26,FR,France
16,202409,7,14337,10871,17803,21,16,26,FR,France
17,202408,7,15899,11991,19807,24,18,30,FR,France
18,202407,7,11294,8226,14362,17,12,22,FR,France
19,202406,7,12174,9020,15328,18,13,23,FR,France
20,202405,7,8814,6110,11518,13,9,17,FR,France
21,202404,7,9504,6566,12442,14,10,18,FR,France
22,202403,7,6948,4633,9263,10,7,13,FR,France
23,202402,7,7125,4852,9398,11,8,14,FR,France
24,202401,7,13305,9214,17396,20,14,26,FR,France
25,202352,7,11636,7354,15918,18,12,24,FR,France
26,202351,7,6912,4227,9597,10,6,14,FR,France
27,202350,7,8799,6215,11383,13,9,17,FR,France
28,202349,7,7817,5362,10272,12,8,16,FR,France
29,202348,7,7351,4749,9953,11,7,15,FR,France
...,...,...,...,...,...,...,...,...,...,...
1721,199126,7,17608,11304,23912,31,20,42,FR,France
1722,199125,7,16169,10700,21638,28,18,38,FR,France
1723,199124,7,16171,10071,22271,28,17,39,FR,France
1724,199123,7,11947,7671,16223,21,13,29,FR,France
1725,199122,7,15452,9953,20951,27,17,37,FR,France
1726,199121,7,14903,8975,20831,26,16,36,FR,France
1727,199120,7,19053,12742,25364,34,23,45,FR,France
1728,199119,7,16739,11246,22232,29,19,39,FR,France
1729,199118,7,21385,13882,28888,38,25,51,FR,France
1730,199117,7,13462,8877,18047,24,16,32,FR,France
1731,199116,7,14857,10068,19646,26,18,34,FR,France
1732,199115,7,13975,9781,18169,25,18,32,FR,France
1733,199114,7,12265,7684,16846,22,14,30,FR,France
1734,199113,7,9567,6041,13093,17,11,23,FR,France
1735,199112,7,10864,7331,14397,19,13,25,FR,France
1736,199111,7,15574,11184,19964,27,19,35,FR,France
1737,199110,7,16643,11372,21914,29,20,38,FR,France
1738,199109,7,13741,8780,18702,24,15,33,FR,France
1739,199108,7,13289,8813,17765,23,15,31,FR,France
1740,199107,7,12337,8077,16597,22,15,29,FR,France
1741,199106,7,10877,7013,14741,19,12,26,FR,France
1742,199105,7,10442,6544,14340,18,11,25,FR,France
1743,199104,7,7913,4563,11263,14,8,20,FR,France
1744,199103,7,15387,10484,20290,27,18,36,FR,France
1745,199102,7,16277,11046,21508,29,20,38,FR,France
1746,199101,7,15565,10271,20859,27,18,36,FR,France
1747,199052,7,19375,13295,25455,34,23,45,FR,France
1748,199051,7,19080,13807,24353,34,25,43,FR,France
1749,199050,7,11079,6660,15498,20,12,28,FR,France
1750,199049,7,1143,0,2610,2,0,5,FR,France

In [3]:
raw_data[raw_data.isnull().any(axis=1)]

Empty DataFrame
Columns: [week, indicator, inc, inc_low, inc_up, inc100, inc100_low, inc100_up, geo_insee, geo_name]
Index: []

no data missing

convert data to year

In [6]:
data = raw_data
def convert_week(year_and_week_int):
    year_and_week_str = str(year_and_week_int)
    year = int(year_and_week_str[:4])
    week = int(year_and_week_str[4:])
    w = isoweek.Week(year, week)
    return pd.Period(w.day(0), 'W')

data['period'] = [convert_week(yw) for yw in data['week']]

In [7]:
sorted_data = data.set_index('period').sort_index()

In [11]:
#see some missing?
periods = sorted_data.index
for p1, p2 in zip(periods[:-1], periods[1:]):
    delta = p2.to_timestamp() - p1.end_time
    if delta > pd.Timedelta('1s'):
        print(p1, p2)

In [22]:
first_august_week = [pd.Period(pd.Timestamp(y, 8, 1), 'W')
                     for y in range(1991,
                                    sorted_data.index[-1].year)]

for i in first_august_week:
    print(i)

1991-07-29/1991-08-04
1992-07-27/1992-08-02
1993-07-26/1993-08-01
1994-08-01/1994-08-07
1995-07-31/1995-08-06
1996-07-29/1996-08-04
1997-07-28/1997-08-03
1998-07-27/1998-08-02
1999-07-26/1999-08-01
2000-07-31/2000-08-06
2001-07-30/2001-08-05
2002-07-29/2002-08-04
2003-07-28/2003-08-03
2004-07-26/2004-08-01
2005-08-01/2005-08-07
2006-07-31/2006-08-06
2007-07-30/2007-08-05
2008-07-28/2008-08-03
2009-07-27/2009-08-02
2010-07-26/2010-08-01
2011-08-01/2011-08-07
2012-07-30/2012-08-05
2013-07-29/2013-08-04
2014-07-28/2014-08-03
2015-07-27/2015-08-02
2016-08-01/2016-08-07
2017-07-31/2017-08-06
2018-07-30/2018-08-05
2019-07-29/2019-08-04
2020-07-27/2020-08-02
2021-07-26/2021-08-01
2022-08-01/2022-08-07
2023-07-31/2023-08-06

In [23]:
import pandas as pd

# Initialize a dictionary to store annual sums
annual_sums = {}

# Iterate over each year's first week of August
for week_start in first_august_week:
    year = week_start.year

    year_data = sorted_data[str(year)]
    annual_sum = year_data['inc'].sum()
    
    # Store the annual sum in the dictionary
    annual_sums[year] = annual_sum

# Print annual sums
for year, total_inc in annual_sums.items():
    print(f"Year {year}: Total 'inc' sum = {total_inc}")

Year 1991: Total 'inc' sum = 679607
Year 1992: Total 'inc' sum = 843500
Year 1993: Total 'inc' sum = 611264
Year 1994: Total 'inc' sum = 670292
Year 1995: Total 'inc' sum = 667294
Year 1996: Total 'inc' sum = 646644
Year 1997: Total 'inc' sum = 643524
Year 1998: Total 'inc' sum = 785055
Year 1999: Total 'inc' sum = 670819
Year 2000: Total 'inc' sum = 656975
Year 2001: Total 'inc' sum = 569744
Year 2002: Total 'inc' sum = 612129
Year 2003: Total 'inc' sum = 703899
Year 2004: Total 'inc' sum = 850765
Year 2005: Total 'inc' sum = 672315
Year 2006: Total 'inc' sum = 574493
Year 2007: Total 'inc' sum = 798899
Year 2008: Total 'inc' sum = 766066
Year 2009: Total 'inc' sum = 875937
Year 2010: Total 'inc' sum = 794691
Year 2011: Total 'inc' sum = 655146
Year 2012: Total 'inc' sum = 720814
Year 2013: Total 'inc' sum = 680822
Year 2014: Total 'inc' sum = 664026
Year 2015: Total 'inc' sum = 649742
Year 2016: Total 'inc' sum = 744389
Year 2017: Total 'inc' sum = 564245
Year 2018: Total 'inc' sum = 577351
Year 2019: Total 'inc' sum = 550709
Year 2020: Total 'inc' sum = 229985
Year 2021: Total 'inc' sum = 441771
Year 2022: Total 'inc' sum = 582916
Year 2023: Total 'inc' sum = 382480

In [24]:
max_sum = max(annual_sums.values())
min_sum = min(annual_sums.values())
print(max_sum)
print(min_sum)

875937
229985